import type { ParkingRecord, ParkingSpot, Coupon } from '@/types';

export const TODAY = new Date();
export const FORMAT_DATE = (d: Date) => d.toISOString().slice(0, 10);

function daysAgo(n: number): string {
  const d = new Date(TODAY);
  d.setDate(d.getDate() - n);
  return FORMAT_DATE(d);
}

function daysLater(n: number): Date {
  const d = new Date(TODAY);
  d.setDate(d.getDate() + n);
  return d;
}

function hoursLater(n: number): Date {
  const d = new Date(TODAY);
  d.setHours(d.getHours() + n);
  return d;
}

function monthsAgoStart(n: number): string {
  const d = new Date(TODAY);
  d.setMonth(d.getMonth() - n);
  d.setDate(1);
  return FORMAT_DATE(d);
}

export const MOCK_RECORDS: ParkingRecord[] = [
  {
    id: 'r1',
    date: FORMAT_DATE(TODAY),
    locationName: '西单大悦城停车场',
    lat: 39.9087,
    lng: 116.3975,
    duration: 120,
    amount: 24,
    paymentMethod: 'qrcode',
    notes: '先停车后扫码，未缴费',
    createdAt: new Date(TODAY.getTime() - 7200000).toISOString(),
    isPrepaid: false,
    paymentDeadline: hoursLater(2).toISOString(),
    reminderEnabled: true,
    reminderSent: false,
    isPaid: false,
  },
  {
    id: 'r2',
    date: FORMAT_DATE(TODAY),
    locationName: '王府井商业街路边',
    lat: 39.9147,
    lng: 116.4103,
    duration: 90,
    amount: 15,
    paymentMethod: 'qrcode',
    notes: '路边电子停车，记得30分钟内缴费',
    createdAt: new Date(TODAY.getTime() - 5400000).toISOString(),
    isPrepaid: false,
    paymentDeadline: hoursLater(0.5).toISOString(),
    reminderEnabled: true,
    reminderSent: false,
    isPaid: false,
  },
  {
    id: 'r3',
    date: daysAgo(1),
    locationName: '公司楼下停车场',
    lat: 39.9087,
    lng: 116.3975,
    duration: 540,
    amount: 45,
    paymentMethod: 'app',
    notes: '早9点到晚6点',
    createdAt: new Date(TODAY.getTime() - 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
  {
    id: 'r4',
    date: daysAgo(2),
    locationName: '家附近小区外',
    lat: 39.9187,
    lng: 116.4075,
    duration: 720,
    amount: 25,
    paymentMethod: 'qrcode',
    createdAt: new Date(TODAY.getTime() - 2 * 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
  {
    id: 'r5',
    date: daysAgo(4),
    locationName: '朝阳大悦城',
    lat: 39.9287,
    lng: 116.5075,
    duration: 180,
    amount: 18,
    paymentMethod: 'cash',
    notes: '购物停车',
    createdAt: new Date(TODAY.getTime() - 4 * 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
  {
    id: 'r6',
    date: daysAgo(6),
    locationName: '公司楼下停车场',
    lat: 39.9087,
    lng: 116.3975,
    duration: 480,
    amount: 40,
    paymentMethod: 'app',
    createdAt: new Date(TODAY.getTime() - 6 * 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
  {
    id: 'r7',
    date: daysAgo(10),
    locationName: '公司楼下停车场',
    lat: 39.9087,
    lng: 116.3975,
    duration: 600,
    amount: 50,
    paymentMethod: 'app',
    createdAt: new Date(TODAY.getTime() - 10 * 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
  {
    id: 'r8',
    date: monthsAgoStart(1).slice(0, 8) + '15',
    locationName: '公司楼下停车场',
    lat: 39.9087,
    lng: 116.3975,
    duration: 540,
    amount: 48,
    paymentMethod: 'app',
    createdAt: new Date(TODAY.getTime() - 30 * 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
  {
    id: 'r9',
    date: monthsAgoStart(1).slice(0, 8) + '20',
    locationName: '家附近小区外',
    lat: 39.9187,
    lng: 116.4075,
    duration: 480,
    amount: 20,
    paymentMethod: 'qrcode',
    createdAt: new Date(TODAY.getTime() - 35 * 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
  {
    id: 'r10',
    date: monthsAgoStart(2).slice(0, 8) + '10',
    locationName: '公司楼下停车场',
    lat: 39.9087,
    lng: 116.3975,
    duration: 540,
    amount: 46,
    paymentMethod: 'app',
    createdAt: new Date(TODAY.getTime() - 60 * 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
  {
    id: 'r11',
    date: monthsAgoStart(3).slice(0, 8) + '05',
    locationName: '三里屯太古里',
    lat: 39.9387,
    lng: 116.4375,
    duration: 240,
    amount: 32,
    paymentMethod: 'qrcode',
    createdAt: new Date(TODAY.getTime() - 90 * 86400000).toISOString(),
    isPrepaid: true,
    reminderEnabled: false,
    reminderSent: false,
    isPaid: true,
  },
];

export const MOCK_SPOT: ParkingSpot = {
  id: 's1',
  spotNumber: 'B2-035',
  floor: 'B2',
  area: 'D区',
  photo: '',
  notes: '电梯口右转第3个',
  createdAt: new Date(TODAY.getTime() - 3600000).toISOString(),
  isActive: true,
};

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'c1',
    name: '商场停车满减券',
    faceValue: 10,
    minAmount: 30,
    condition: 'min_amount',
    conditionDescription: '满30元减10元',
    validFrom: daysAgo(5),
    validTo: daysLater(2).toISOString().slice(0, 10),
    isUsed: false,
    reminderSent: false,
    createdAt: new Date(TODAY.getTime() - 5 * 86400000).toISOString(),
    notes: '西单大悦城消费赠送',
  },
  {
    id: 'c2',
    name: '周末停车优惠券',
    faceValue: 15,
    condition: 'weekend_only',
    conditionDescription: '仅限周末使用',
    validFrom: daysAgo(3),
    validTo: daysLater(7).toISOString().slice(0, 10),
    isUsed: false,
    reminderSent: false,
    createdAt: new Date(TODAY.getTime() - 3 * 86400000).toISOString(),
  },
  {
    id: 'c3',
    name: '工作日无门槛券',
    faceValue: 5,
    condition: 'none',
    conditionDescription: '无门槛使用',
    validFrom: daysAgo(10),
    validTo: daysLater(1).toISOString().slice(0, 10),
    isUsed: false,
    reminderSent: false,
    createdAt: new Date(TODAY.getTime() - 10 * 86400000).toISOString(),
    notes: 'App 签到赠送',
  },
  {
    id: 'c4',
    name: '节假日停车券',
    faceValue: 20,
    condition: 'holiday_only',
    conditionDescription: '仅限节假日使用',
    validFrom: daysAgo(1),
    validTo: daysLater(30).toISOString().slice(0, 10),
    isUsed: false,
    reminderSent: false,
    createdAt: new Date(TODAY.getTime() - 86400000).toISOString(),
  },
  {
    id: 'c5',
    name: '公司附近停车券',
    faceValue: 8,
    condition: 'weekday_only',
    conditionDescription: '仅限工作日使用',
    validFrom: daysAgo(20),
    validTo: daysAgo(5),
    isUsed: true,
    usedRecordId: 'r3',
    reminderSent: false,
    createdAt: new Date(TODAY.getTime() - 20 * 86400000).toISOString(),
  },
  {
    id: 'c6',
    name: '小区停车券',
    faceValue: 12,
    condition: 'none',
    conditionDescription: '无门槛使用',
    validFrom: daysAgo(30),
    validTo: daysAgo(10),
    isUsed: false,
    reminderSent: false,
    createdAt: new Date(TODAY.getTime() - 30 * 86400000).toISOString(),
  },
];
